[package]
name = "localchat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
crossterm = "0.27.0"
env_logger = "0.11.5"
log = "0.4.22"
threadpool = "1.8.1"
